export const Config = {
  CANVAS_ID: "gameCanvas",
  ASPECT_RATIO: 16 / 9,
  BACKGROUND: "#000",
  FIRE_DELAY: 250,
  POINTS_PER_ASTEROID: 100,
  INITIAL_ASTEROID_COUNT: 5,
  DIFFICULTY_INTERVAL: 1000,
  INITIAL_LIVES: 3,
  LIFE_COLOR: "#ffff",
  GAME_OVER_FONT: "40px Arial",
};
